### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by llaville** [llaville/php-compat-info#248]
New major version 6.0 will : 

- [ ] drop support of PHP 5 for version 6.0
- [ ] remove direct dependency to php-reflect
- [ ] remove undirect dependency to umlwriter

**Comment by llaville** [comment]
Last version of branch 5.x is now 5.2.0 that will : 

- [X] be fully compatible PHP 7.2 (removed `each` usage)
- [X] installation is compatible with compatinfo-db 1.x (for PHP 5 users) and compatinfo-db 2.x (for PHP 7 users only)

**Comment by llaville** [comment]
Version 5.2.0 is both for PHP 5 and PHP 7 users:

Certified by tests.

**5.6**
```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

Runtime:       PHP 5.6.40 with Xdebug 2.4.1
Configuration: /shared/httpd/php-compat-info/phpunit.xml.dist

..........................................                        42 / 42 (100%)

Time: 2.11 seconds, Memory: 29.25MB

OK (42 tests, 60 assertions)
```
**7.1**
```
PHPUnit 7.5.12 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.1.29 with Xdebug 2.7.2
Configuration: /shared/httpd/php-compat-info/phpunit.xml.dist

..........................................                        42 / 42 (100%)

Time: 1.95 seconds, Memory: 18.00 MB

OK (42 tests, 60 assertions)
```
**7.2**
```
PHPUnit 7.5.12 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.2.18 with Xdebug 2.7.2
Configuration: /shared/httpd/php-compat-info/phpunit.xml.dist

..........................................                        42 / 42 (100%)

Time: 1.97 seconds, Memory: 18.00 MB

OK (42 tests, 60 assertions)
```
**7.3**
```
PHPUnit 7.5.12 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.5 with Xdebug 2.7.2
Configuration: /shared/httpd/php-compat-info/phpunit.xml.dist

..........................................                        42 / 42 (100%)

Time: 2.03 seconds, Memory: 18.00 MB

OK (42 tests, 60 assertions)
```

**Comment by szepeviktor** [comment]
> distribute PHAR version through Phive

💡 CI can build & sign & upload the PHAR file and the signature too.

**Comment by llaville** [comment]
Composer Automation to build PHAR distribution was removed (see issue with CI about `humbug/box` and PHP 8 platform support: #271 , #270)

**Comment by llaville** [comment]
Follows changes on https://github.com/llaville/php-compat-info/projects/2

**Comment by llaville** [comment]
With one year of delay, I've decided to transfer some expected new features in v6.1, to be able to release soon the v6.0
