### ISSUE TITLE
ROADMAP-v5.4

### ISSUE THREAD

**Issue by llaville** [llaville/php-compat-info#266]
## New minor version 5.4 :

**Must Have**
 
- [X] removes `jean85/pretty-package-versions` package and handle application version with new strategy (to allows) : composer/git outside world and of course composer installation or git clone repository
- [X] reorganizes **compatibility** analyser to use Sniffs to improve maintainbility 
- [X] adds more sniffs to enhance PHP 5/7 features detection 
  - [X] add `DeclareSniff` - see #268 
  - [X] use `AnonymousClassSniff` - see #269 
  - [X] use `ReturnTypeDeclarationSniff` - see #233 
  - [X] add `ParamTypeDeclarationSniff` - see #273 and extract from `VersionResolverVisitor`
  - [X] add `ReservedSniff` - see #186 
  - [X] use `NullCoalesceOperatorSniff` instead of internal compatibility analyser code to solve issue #260 
  - [X] use `PowOperatorSniff ` (renamed from `ExponantiationSniff`) to fully solve issues #142 and #211 
  - [X] add `UseTraitSniff` to solve issue #227 
  - [X] use `ClassMemberAccessSniff` to solve issue #154 
  - [X] add `GeneratorSniff` to solve issue #226 
  - [X] add `GotoSniff` to solve issue #200 
  - [X] add `EmptySniff` to solve issues #207, #238  
  - [X] add `PropertyDeclarationSniff` to solve issue #119
  - [X] use `MagicClassConstantSniff` to solve issue #218  
  - [X] add `CryptStringSniff` to solve issue #220 
- [X] replaces metrics structure by an OOP mechanism. Like Symfony Profiler/Profile/DataCollector
- [X] rewrites full documentation in MarkDown format
- [X] fix all Unit Tests - delayed to solve issue #274 
- [X] handle conditional code

**Nice to have**

- [ ] ~distribute PHAR version through Phive - see #270~ delayed to v6.0
- [ ] ~add github actions as Continous Integration Workflow - see #271~ delayed to v6.0

**Release Schedule**

- 5.4.0 stable planned for September ~9~ (later), 2020

**Comment by llaville** [comment]
Reorganization of compatibility analyser code to accept sniffs is now acheived to 90%. Should be push to branch 5.4 tomorrow and allows to keep continue to solve issue like #186

**Comment by llaville** [comment]
Reorganization of compatibility analyser code to accept sniffs is now acheived to 100% (see commit 2e5c720d56eeffc98a2e49d64836dcbdf12ad094)

Unit Tests (upgraded to PHP 7 syntax, see commit 0cfb9f52f65edc2d78fde4448a60e85e4631592d) pass at 100% 

Now, a second optimization phase should be apply to extract code and transform to standalone sniff.
Previous phase allowed to reduce compatibility analyser code by about 300 lines.

**Comment by llaville** [comment]
Before to continue to integrate Sniffs to detect each single features, I'll rework base code of compatibility analyser to use an OOP mechanism like  Symfony Profiler/Profile/DataCollector

**Comment by llaville** [comment]
I've begin to rewrite the full documentation in MarkDown format (rather than AsciiDoc).
Elements that I consider stable are the node visitors of the new architecture explained in the [docs](https://github.com/llaville/php-compat-info/tree/5.4/docs) folder.

Code refactoring is still on way, and spliting features by sniffs rather that includes in monolitic `compatibility` analyser.

**Comment by llaville** [comment]
First issue on `ParentContextVisitor` was fixed with commit https://github.com/llaville/php-compat-info/commit/ffa114689d4f55e9fdd78c6dc51529076dee9f5d.

I've also decided to add part of PHP_Reflect code into CompatInfo Application to make it more decoupled especially for analyser run command. It will allow to make change to CompatInfo without need to release a new PHP_Reflect version.
The code will look like a bit ugly, but it will help me to prepare a better core architecture for v5.4 and future v6.0

Tomorrow I'll push on repository a running 5.4 application, not yet optimised, but in good way, and of course with a better PHP 7 features detection. At least more than 5.2 / 5.3

**Comment by llaville** [comment]
`ReturnTypeDeclarationSniff` must be fixed to solve #273

**Comment by llaville** [comment]
There is lot of work to do : 
- refactor all remaining `leave` methods (prefixed by **_**) to deactivated code temporary
- and decouple Reflect part from CompatInfo (but this huge work is for v6.0). Currently code added allow to run the `analyser:run` command with compatibility analyser

All commands are not reintegrated, but only the minimum required: 

```
        _            ____                            _   ___        __
  _ __ | |__  _ __  / ___|___  _ __ ___  _ __   __ _| |_|_ _|_ __  / _| ___
 | '_ \| '_ \| '_ \| |   / _ \| '_ ` _ \| '_ \ / _` | __|| || '_ \| |_ / _ \
 | |_) | | | | |_) | |__| (_) | | | | | | |_) | (_| | |_ | || | | |  _| (_) |
 | .__/|_| |_| .__/ \____\___/|_| |_| |_| .__/ \__,_|\__|___|_| |_|_|  \___/
 |_|         |_|                        |_|

phpCompatInfo version 5.4.x-dev DB version 2.16.0 built Jul 11 2020 08:19:48 UTC

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-plugins      Disables all plugins.
      --profile         Display timing and memory usage information.
      --progress        Show progress bar.
      --output=OUTPUT   Write results to file or URL.
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  help            Displays help for a command
  list            Lists commands
 analyser
  analyser:list   List all analysers available.
  analyser:run    Analyse a data source and display results.
 reference
  reference:list  List all references supported.
  reference:show  Show information about a reference.
```

- fix all unit tests
- and probably lot more ...

I'll appreciate a lot if some of you can give me some feedback. Feel free to post issue, if you found or need new Sniff for PHP 7 features detection.

Thanks.

**=> The first beta code running of 5.4 is available in this repository (branch 5.4)**

**Comment by llaville** [comment]
The release candidate for 5.4 is canceled. As I've received no feedback since the version on branch 5.4 is available and pretty stable, I think its useless to publish an RC.
Final version stable is always planned for September 9.

**Comment by llaville** [comment]
Major release 6.0.0 (that should come after 5.4.0) will have a Command Line Interface revisited (and simplified by removing PHP Reflect dependency)
With this goal, i've begin to reduced useless features in API v5 : 
- command `analyser:list` was removed
- plugins system was removed
- configuration file `phpcompatinfo.json` and env var ` BARTLETT_SCAN_DIR` and ` BARTLETTRC` were removed

See commit c0959a1057007136af51d849920056896f0c7c94

**Comment by llaville** [comment]
**Nice to have** tasks will be add in v6.0, not v5.4 (sorry)

Last task to finish is to fix issue #274. I should be able to fix it tomorrow and release v5.4.0 final stable  Wednesday 30 september.

Last chance, if somebody will give a feedback of current version in branch 5.4 / CHANGELOG should up-to-date now !

**Comment by llaville** [comment]
I'm proud to announce after 3 months of active development that the final release 5.4.0 (stable) is on way !
Will be publish in few minutes now.
